/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package event_management;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
//import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
//import java.text.SimpleDateFormat;
//import java.text.DateFormat;



import javax.swing.JOptionPane;

/**
 *
 * @author jeeva
 */
public class event_details extends javax.swing.JFrame {
  

    /**
     * Creates new form event_details
     */
    public event_details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtlocation = new javax.swing.JTextField();
        veg = new javax.swing.JRadioButton();
        nonveg = new javax.swing.JRadioButton();
        veg_nonveg = new javax.swing.JRadioButton();
        notneeded = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("EVENTS DETAILS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 330, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Event_name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Location");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 190, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Catering");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Decoration");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 100, -1));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 273, -1));
        jPanel1.add(txtlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 273, -1));

        buttonGroup1.add(veg);
        veg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        veg.setText("Veg");
        veg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vegMouseClicked(evt);
            }
        });
        veg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegActionPerformed(evt);
            }
        });
        jPanel1.add(veg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 98, -1));

        buttonGroup1.add(nonveg);
        nonveg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nonveg.setText("Non-Veg");
        nonveg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nonvegMouseClicked(evt);
            }
        });
        nonveg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonvegActionPerformed(evt);
            }
        });
        jPanel1.add(nonveg, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 98, -1));

        buttonGroup1.add(veg_nonveg);
        veg_nonveg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        veg_nonveg.setText("Veg+Non-Veg");
        veg_nonveg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                veg_nonvegMouseClicked(evt);
            }
        });
        veg_nonveg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veg_nonvegActionPerformed(evt);
            }
        });
        jPanel1.add(veg_nonveg, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 114, -1));

        buttonGroup1.add(notneeded);
        notneeded.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        notneeded.setText("not needed");
        notneeded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notneededActionPerformed(evt);
            }
        });
        jPanel1.add(notneeded, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 98, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Event_id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 60, 90, -1));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 135, -1));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setText("Flowers and lights");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 145, -1));

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setText("Not needed");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 98, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 226, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 120, -1));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pexels-craig-adderley-2306281.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vegMouseClicked
             JOptionPane.showMessageDialog(this,"paneer\n"
                     + "manchurian\n"
                     + "mushroom");        // TODO add your handling code here:
    }//GEN-LAST:event_vegMouseClicked

    private void nonvegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nonvegMouseClicked
           JOptionPane.showMessageDialog(this,"chicken masala\n"
                   + "chicken lollypop\n"
                   + "chicken kohlapuri ");        // TODO add your handling code here:
    }//GEN-LAST:event_nonvegMouseClicked

    private void veg_nonvegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_veg_nonvegMouseClicked
 JOptionPane.showMessageDialog(this,"chicken masala\n"
                   + "chicken lollypop\n"
                   + " chicken kohlapuri\n"+"paneer\n"
                   + "mavnchurian\n"
                   + "mushroom");        // TODO add your handling code here:
    }//GEN-LAST:event_veg_nonvegMouseClicked

    private void vegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegActionPerformed
                 food="veg";
                 // TODO add your handling code here:
    }//GEN-LAST:event_vegActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(txtid.getText().equals("")){ 
            JOptionPane.showMessageDialog(this,"All values are mandatory");
             txtid.requestFocus();
        }
              else if (txtname.getText().equals("")){
              JOptionPane.showMessageDialog(this,"All values are mandatory");
              txtname.requestFocus();
 }
          else if (txtlocation.getText().equals("")){
              JOptionPane.showMessageDialog(this,"All values are mandatory");
              txtlocation.requestFocus();
  }
          else{
                    Connection con =null;
            Statement st=null;
            PreparedStatement pst=null;
            ResultSet rs=null;
         
              try {
                   
             
                  Class.forName("com.mysql.cj.jdbc.Driver");
                  con=DriverManager.getConnection("jdbc:mysql://localhost:3360/event_management","root","jeevan@123");
                  pst =con.prepareStatement("select * from events where Eid=?");
                  pst.setString(1,txtid.getText());
                  rs=pst.executeQuery();
                  if(rs.next()){
                      JOptionPane.showMessageDialog(this,"It already exists");
                      
                 
              } 
                  else
                  {
               
                      pst=con.prepareStatement("insert into events(Eid, event_name,date,food,decoration,location)values(?,?,?,?,?,?)");
                      pst.setString(1,txtid.getText());
                      pst.setString(2,txtname.getText());
                     // DateFormat dateFormat=new SimpleDateFormat("dd/mm/yyyy");
                      Date date=new Date();
                      java.sql.Date sqldate=new java.sql.Date(date.getTime());
                      pst.setDate(3,sqldate);
                    // pst.setString(3,java.sql.Date date=new java.sql.Date (Calendar.getInstance().getTime().getTime()));
                      pst.setString(4,food);
                      pst.setString(5,decoration);
                      pst.setString(6,txtlocation.getText());
                      pst.executeUpdate();
                       JOptionPane.showMessageDialog(this,"your entries have been stored");
                      
                  }
                  
              }
              
              catch (ClassNotFoundException ex) {
                  Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
              } catch (SQLException ex) {
                  Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
              }
              
              
              
              
              
          }

              
    
    
    

















// TODO add your handling code here:
            
    }//GEN-LAST:event_jButton1MouseClicked

    private void nonvegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonvegActionPerformed
               food="nonveg";
    }//GEN-LAST:event_nonvegActionPerformed

    private void veg_nonvegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veg_nonvegActionPerformed
                 food="veg and nonveg";        // TODO add your handling code here:
    }//GEN-LAST:event_veg_nonvegActionPerformed

    private void notneededActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notneededActionPerformed
                 food="not needed"; // TODO add your handling code here:
    }//GEN-LAST:event_notneededActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
                   decoration="flowers and lights";        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       decoration="not needed";   // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new bill().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(event_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(event_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(event_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(event_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new event_details().setVisible(true);
            }
        });
    }
private String food;
private String decoration;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton nonveg;
    private javax.swing.JRadioButton notneeded;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtname;
    private javax.swing.JRadioButton veg;
    private javax.swing.JRadioButton veg_nonveg;
    // End of variables declaration//GEN-END:variables
}///^[0-9]+$/
